parameters:
  wendall.fieldtype.color.identifier: 'wendallcolor'

services:
  Wendall\eZColorPicker\FieldType\ColorPicker\Type:
    autoconfigure: false
    autowire: true
    public: true
    calls:
      - [ 'setColorConverter', ["@Wendall\\ColorConverter\\ColorConverter"] ]
    tags:
      - { name: ezplatform.field_type, alias: "%wendall.fieldtype.color.identifier%" }
      - { name: ezplatform.field_type.form_mapper.value, fieldType: "%wendall.fieldtype.color.identifier%" }
      - { name: ezplatform.field_type.form_mapper.definition, fieldType: "%wendall.fieldtype.color.identifier%" }

  wendall.ezcolorpicker.fieldtype.colorpicker.type.notindexable:
    class: eZ\Publish\Core\FieldType\Unindexed
    tags:
      - { name: ezplatform.field_type.indexable, alias: "%wendall.fieldtype.color.identifier%" }

